# -*- coding: utf-8 -*-
"""task11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KYJ-O68clkdDT664zEIe_HJzDf2_6Wn
"""



from pandas import *

# read CSV file
hfx_data = read_csv("Trails.csv")
 
# convert column data to list
TRAIL_ID = hfx_data['TRAIL_ID'].tolist()
TRAIL_NAME = hfx_data['TRAIL_NAME'].tolist()
gen_condition = hfx_data['CONDITION'].tolist()
print('TRAIL_ID:', TRAIL_ID)
print('TRAIL_NAME',TRAIL_NAME)
print('gen_condition:', gen_condition)

# read CSV file
hfx_data = read_csv("Trails.csv")
 
# convert column data to list
TRAIL_ID = hfx_data['TRAIL_ID'].tolist()
TRAIL_NAME = hfx_data['TRAIL_NAME'].tolist()
gen_condition = hfx_data['CONDITION'].tolist()
print('TRAIL_ID:', TRAIL_ID)
print('TRAIL_NAME',TRAIL_NAME)
print('gen_condition:', gen_condition)



"""# New Section"""