# -*- coding: utf-8 -*-
"""task13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KYJ-O68clkdDT664zEIe_HJzDf2_6Wn
"""



from pandas import *
 
# read CSV file
hfx_data = read_csv("Trails.csv")
 
# convert column data-list

Stat_activity = hfx_data['STATUS'].tolist()
stat_cnt=0
for item in Stat_activity:
  if item=='ACTIVE':
    stat_cnt=stat_cnt+1
print(stat_cnt) 

lighting = hfx_data['LIGHT'].tolist()
light_cnt=0
for item in lighting:
  if item=='Yes':
    light_cnt=light_cnt+1
print(light_cnt)



"""# New Section"""