# -*- coding: utf-8 -*-
"""task12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KYJ-O68clkdDT664zEIe_HJzDf2_6Wn
"""



from pandas import *
 
# read CSV file
hfx_data = read_csv("Trails.csv")
# convert column data to list

inst_yr =hfx_data['INST_YEAR'].tolist()
count=0
for item in inst_yr:
  if item>2000:
    count=count+1
print(count)



"""# New Section"""